export const ActionTypes = {
  SET_USERS: 'SET_USERS',
  SELECTED_COLUMNS: 'SELECTED_COLUMNS',
  REMOVE_SELECTED_COLUMN: 'REMOVE_SELECTED_COLUMN',
  SET_NEW_COLUMNS: 'SET_NEW_COLUMNS',
  DRAG_COLUMN: 'DRAG_COLUMN',
};
